# -*- coding: utf-8 -*-
"""WorldData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kI4dMkPcOLfKHpcgmOLS_yCetvrEWk9g
"""

from urllib.request import urlopen
import json
import pandas as pd
import requests

def fetch_worldbank_data():
    url = "http://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=jsonstat"

    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for 4xx or 5xx status codes
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print("Error fetching data:", e)
        return None

# Fetch data from World Bank API
worldbank_data = fetch_worldbank_data()

# Check if data was fetched successfully
if worldbank_data:
    print("Data fetched successfully!")
    # For example, you can print the data
    print(worldbank_data)
else:
    print("Failed to fetch data from World Bank API.")



