# -*- coding: utf-8 -*-
"""eplplayer_country.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152LE0vSREMgxG4pa2IQbuvND6or-GN9N
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import substring


spark = SparkSession.builder.appName("read_csv").getOrCreate()
country_df = spark.read.format("csv").option("header", "true").load("/content/countries_code_data_2024-04-30 16_35_36.535473 (1).csv")
epl_df = spark.read.format("csv").option("header", "true").load("/content/epl_players_data_2024-04-30 14_25_17.543472 (1).csv")

joined_df = country_df.join(epl_df, country_df.id == epl_df.country_id, "left")

joined_df = joined_df.withColumnRenamed("name", "country_name").select("display_name", "firstname", "lastname", "date_of_birth", "country_name", "iso3")

# Remove nulls from the joined_df
joined_df = joined_df.dropna()

# Create a year column using the date_of_birth column
joined_df = joined_df.withColumn("birth_year", substring("date_of_birth", 1, 4))

# Show the joined_df with the new year column
joined_df.show()