# -*- coding: utf-8 -*-
"""f1_racer_country.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpiuBpqVBXy8B2lzikQQLxTJ1qMCQznB
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import expr


spark = SparkSession.builder.appName("read_csv").getOrCreate()

spark = SparkSession.builder.getOrCreate()

country_df = spark.read.csv("/content/countries_code_data_2024-04-30 16_35_36.535473 (1).csv", header=True, inferSchema=True)
driver_df = spark.read.csv("/content/f1_driver_data_2024-04-30 15_06_28.721922 (1).csv", header=True, inferSchema=True)

driver_df = driver_df.withColumn("country_code", expr("CASE WHEN country_code == 'NED' THEN 'NLD' ELSE country_code END"))

joined_df = country_df.join(driver_df, country_df.iso3 == driver_df.country_code, "inner")
joined_df = joined_df.withColumnRenamed("name", "country_name").select("driver_number", "full_name", "name_acronym", "first_name", "last_name", "country_name","iso3")
joined_df.show()